spring:
  datasource:
    url: jdbc:mysql://ip:port/excel?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: 你自己的用户名 #你自己的用户名
    password: 你自己的密码 #你自己的密码
  application:
    name: excel-demo


server:
  port: 8081
# xml的位置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml